baseurl: "" # the subpath of your site, e.g. /blog/
encoding: utf-8
markdown: kramdown
collections:
  poems:
    title: Poems
    output: true
  stories:
    title: Stories
    output: true
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
